export const ActionTypes = {
    SET_PRODUCT : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELETED_PRODUCT",
    SET_PRODUCT_MODAL : "SET_PRODUCT_MODAL"
}